# Generated by Django 3.2.5 on 2021-07-07 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210707_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='record',
            name='habit_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.habit'),
        ),
    ]
