# Generated by Django 3.2.5 on 2021-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210707_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_date',
            field=models.DateField(),
        ),
    ]
