# Generated by Django 3.2.5 on 2021-07-07 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_habit_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
