# Generated by Django 3.2.5 on 2021-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_habit_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='performance',
            field=models.IntegerField(null=True),
        ),
    ]
