# Generated by Django 3.2.5 on 2021-07-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210707_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_date',
        ),
    ]
