# Generated by Django 3.2.5 on 2021-07-07 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_habit_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
