# Generated by Django 3.2.5 on 2021-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_habit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
